### ISSUE TITLE
An inquiry about storage information

### ISSUE THREAD

**Issue by mj0704** [maincold2/Dynamic_C3DGS#1]
Hello, thanks for your effort.

I leave this inquiry because there is some storage mismatch between the paper and the result from my environment.
For example, I got the following result(content in 'storage' file) for **'flame salmon' dataset.**
However, the output storage of the dataset is denoted as **26.8MB in the paper.**

Storage
position: 0.385278
motion: 1.155834
scale: 0.26914000000000005
rotation: 0.27323600000000003
omega: 0.201855
time_feature: 0.204927
opacity: 0.128426
time_center: 0.128426
time_scale: 0.128426
hash: 0.989184
mlp: 0.014336
**total: 3.8790680000000006 MB**

As another example, I got the following result for **'sear steak' dataset.**
However, the output storage of the dataset is denoted as **19.0MB in the paper.**

Storage
position: 0.24048
motion: 0.72144
scale: 0.17260799999999998
rotation: 0.176704
omega: 0.129456
time_feature: 0.132528
opacity: 0.08016
time_center: 0.08016
time_scale: 0.08016
hash: 0.989184
mlp: 0.014336
**total: 2.817216 MB**

In both cases, **I got much smaller size than the values in the paper.**
I also checked that the sizes of 'npz' files are equal to the value in the 'storage' file.
Furthermore, I also checked that there is negligible storage mismatch in case of static scene(mip-NeRF dataset) with similar environment.

I expect that there is something wrong in my environment.
1. Could you provide storage breakdown information(i.e. 'storage' file content) of 'flame salmon' and 'sear steak' dataset?
2. Could you give me some other advices?
Thank you!

**Comment by maincold2** [comment]
It seems the right results because the values in the paper refer to storage of 300 frames.
We follow STG, which represents 50 frames per model, and sum up the storage of 6 models.

Thanks!

**Comment by mj0704** [comment]
Thank you!
Your answer was really helpful.
